services:

  api:
    build:
      context: .
      dockerfile: Dockerfile

    ports:
      - "8080:8080"

    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ConnectionStrings__DefaultConnection: "Server=sqlserver,1433;Database=CRN_Assessment;User Id=sa;Password=Atharva@vl2254$;TrustServerCertificate=True;"

    depends_on:
      - sqlserver


  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest

    environment:
      ACCEPT_EULA: "Y"
      MSSQL_SA_PASSWORD: "Atharva@vl2254$"

    ports:
      - "1433:1433"

    volumes:
      - sqlserver_data:/var/opt/mssql


volumes:
  sqlserver_data: